### ISSUE TITLE
Random spanish stuff posted by the bot with my account in the chat

### ISSUE THREAD

**Issue by ReneDussault** [ciskosv/BanTwithLurkerBots#1]
please can you leave a tutorial on how to disable the random spanish messages that the bot leaves in the chat.. you should warn people that his behavior is hard coded in the bot.

QUICK EDIT: i dont know if i broke something by doing so, but i commented out with // the places in the code where i saw CPH.SendMessage

thank you

**Comment by ciskosv** [comment]
Thanks for letting me know about it, I just edited the readme file, what you did is exactly what's needed to be done if you don't want any message in the chat.
